apiVersion: v1
kind: Service
metadata:
  name: svc-wafapp
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: app-wafapp
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-wafapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-wafapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-wafapp
    spec:
      containers:
      - env:
        - name: GO_ENV
          value: production
        image: codeboe/content-info:4.0
        imagePullPolicy: Always
        name: waf-app
        ports:
        - containerPort: 3000
          protocol: TCP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wafapp
spec:
  rules:
  - host: wafapp.harshpanchal.in
    http:
      paths:
      - backend:
          service:
            name: svc-wafapp
            port:
              number: 3000
        path: /
        pathType: Prefix
